export const siteConfig = {
  brandName: "Tobias Ponce de Leon",
  brandShort: "TPDL",
  phoneDisplay: "11 3185-7044",
  whatsappNumber: "5491131857044",
  email: "tobiasponcedeleon@hotmail.com.ar",
  instagram: "https://www.instagram.com/tobixpdl/",
  domain: "https://tobiasponcedeleon.com.ar/",
  startingPrice: 42000,
  prices: {
    presence: 42000,
    catalog: 78000,
    orders: 125000,
    managedCatalog: 150000,
    bookings: 95000,
    store: 250000,
  },
  colors: {
    background: "#0E1726",
    surface: "#142235",
    light: "#F6F1E8",
    action: "#FF6B35",
    accent: "#2EC4B6",
    textLight: "#F8FAFC",
    textDark: "#172033",
    textMuted: "#AAB4C0",
  },
  messages: {
    general: "Hola, vi tu página y quisiera solicitar una cotización sin cargo para mi negocio.",
    presence: "Hola, quisiera solicitar una cotización por el Plan Presencia de $42.000.",
    catalog: "Hola, quisiera solicitar una cotización por una página con catálogo o menú.",
    orders: "Hola, quisiera solicitar una cotización por una página con carrito y pedidos por WhatsApp.",
    managedCatalog: "Hola, quisiera solicitar una cotización por un catálogo autoadministrable.",
    bookings: "Hola, quisiera solicitar una cotización por un sistema de reservas o presupuestos.",
    store: "Hola, quisiera solicitar una cotización por una tienda online.",
  },
} as const;
